ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Models/Service.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LogisticManagerWorkspace.Models
{
    public class Service
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Date { get; set; }

        public string ClientName { get; set; }

        public string Cost { get; set; }

        public string Status { get; set; }

        public Service()
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Date = Date;
            this.ClientName = ClientName;
            this.Cost = Cost;
            this.Status = Status;
        }
    }
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Controllers/ServicesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using LogisticManagerWorkspace.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LogisticManagerWorkspace.Controllers
{
    [Bind("Id,Name,Description,Date,ClientName,Cost,Status")]
    public class ServicesController : Controller
    {
        private readonly LogisticManagerWorkspaceContext _context;

        public ServicesController(LogisticManagerWorkspaceContext context)
        {
            _context = context;
        }

        // GET: Services List: /Services/
        public async Task<IActionResult> Index(string searchString)
        {
            var services = from m in _context.Services
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                services = services.Where(s => s.Name.Contains(searchString));
            }

            return View(await services.ToListAsync());
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "Поиск по фразе: " + searchString;
        }

        // POST: Services: /Services/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categories = from m in _context.Categories
                             select m.Name;
            var clients = from m in _context.Clients
                          select m.Name;
            var statuses = from m in _context.Statuses
                          select m.Name;
            var service = await _context.Services.FindAsync(id);

            var clientServiceViewModel = new ClientServiceViewModel
            {
                Categories = new SelectList(await categories.ToListAsync()),
                Clients = new SelectList(await clients.ToListAsync()),
                Statuses = new SelectList(await statuses.ToListAsync()),
                Service = service
            };

            if (service == null)
            {
                return NotFound();
            }
            return View(clientServiceViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Date,ClientName,Cost,Status")] Service service)
        {
            var serviceResult = new Service
            {
                Id = service.Id,
                Name = service.Name,
                Description = service.Description,
                Date = service.Date,
                ClientName = service.ClientName,
                Cost = service.Cost,
                Status = service.Status
            };

            if (ModelState.IsValid)
            {
                try
                {
                    
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(serviceResult);
        }

        // GET: /Services/Create
        public async Task<IActionResult> CreateAsync()
        {
            var categories = from m in _context.Categories
                             select m.Name;
            var clients = from m in _context.Clients
                          select m.Name;
            var statuses = from m in _context.Statuses
                           select m.Name;
            var service = new Service();

            var clientServiceViewModel = new ClientServiceViewModel
            {
                Categories = new SelectList(await categories.ToListAsync()),
                Clients = new SelectList(await clients.ToListAsync()),
                Statuses = new SelectList(await statuses.ToListAsync()),
                Service = service
            };

            return View(clientServiceViewModel);
        }

        // POST: /Services/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Date,ClientName,Cost,Status")] Service service)
        {
            var serviceResult = new Service
            {
                Name = service.Name,
                Description = service.Description,
                Date = service.Date,
                ClientName = service.ClientName,
                Cost = service.Cost,
                Status = service.Status
            };

            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }

            return View(serviceResult);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            _context.Services.Remove(service);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(object Id)
        {
            throw new NotImplementedException();
        }
    }
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Services/Create.cshtml
@model LogisticManagerWorkspace.Models.ClientServiceViewModel

@{
    ViewData["Title"] = "Создание";
}

<h1>Редактирование:</h1>

<h4>Услуга "@Html.DisplayFor(model => Model.Service.Name)":</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Service.Name" class="control-label"></label>
                <select asp-for="Service.Name" asp-items="Model.Categories">
                    <option value="">Без категории</option>
                </select>
                <span asp-validation-for="Service.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Description" class="control-label"></label>
                <input asp-for="Service.Description" class="form-control" />
                <span asp-validation-for="Service.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Date" class="control-label"></label>
                <input asp-for="Service.Date" class="form-control" />
                <span asp-validation-for="Service.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.ClientName" class="control-label"></label>
                <select asp-for="Service.ClientName" asp-items="Model.Clients">
                    <option value="">All</option>
                </select>
                <span asp-validation-for="Service.ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Cost" class="control-label"></label>
                <input asp-for="Service.Cost" class="form-control" />
                <span asp-validation-for="Service.Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Status" class="control-label"></label>
                <select asp-for="Service.Status" asp-items="Model.Statuses">
                    <option value="">Без статуса</option>
                </select>
                <span asp-validation-for="Service.Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Services/Details.cshtml
@model LogisticManagerWorkspace.Models.Service

@{
    ViewData["Title"] = "Услуга " + Model.Name;
}

    <div>
        <h4>Услуга "@Html.DisplayFor(model => model.Name)":</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ClientName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ClientName)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Cost)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Cost)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Status)
            </dd>
        </dl>
    </div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-action="Index">Назад к списку</a>
</div>

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Services/Edit.cshtml
@model LogisticManagerWorkspace.Models.ClientServiceViewModel

@{
    ViewData["Title"] = "Редактирование";
}

<h1>Редактирование:</h1>

<h4>Услуга</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Service.Id" />
            <div class="form-group">
                <p><b>Id</b> #@Model.Service.Id</p>
            </div>
            <div class="form-group">
                <label asp-for="Service.Name" class="control-label"></label>
                <select asp-for="Service.Name" asp-items="Model.Categories">
                    <option value="">Без категории</option>
                </select>
                <span asp-validation-for="Service.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Description" class="control-label"></label>
                <input asp-for="Service.Description" class="form-control" />
                <span asp-validation-for="Service.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Date" class="control-label"></label>
                <input asp-for="Service.Date" class="form-control" />
                <span asp-validation-for="Service.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.ClientName" class="control-label"></label>
                <select asp-for="Service.ClientName" asp-items="Model.Clients">
                    <option value="">All</option>
                </select>
                <span asp-validation-for="Service.ClientName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Cost" class="control-label"></label>
                <input asp-for="Service.Cost" class="form-control" />
                <span asp-validation-for="Service.Cost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Service.Status" class="control-label"></label>
                <select asp-for="Service.Status" asp-items="Model.Statuses">
                    <option value="">Без статуса</option>
                </select>
                <span asp-validation-for="Service.Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Services/Index.cshtml
@model IEnumerable<LogisticManagerWorkspace.Models.Service>
@{
    ViewData["Title"] = "Услуги";
}

<h2>Услуги</h2>

<p>Услуги, предоставляемые клиентам:</p>

<p>
    <a asp-action="Create">Добавить</a>
</p>

<form asp-controller="Services" asp-action="Index" method="get">
    <p>
        Поиск по названию: <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
        <a asp-action="Index" class="btn btn-alert">Очистить</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClientName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактирование</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
        }
    </tbody>
</table>