ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Controllers/StatusesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using LogisticManagerWorkspace.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LogisticManagerWorkspace.Controllers
{
    public class StatusesController : Controller
    {
        private readonly LogisticManagerWorkspaceContext _context;

        public StatusesController(LogisticManagerWorkspaceContext context)
        {
            _context = context;
        }

        // GET Statuses List: /<controller>/
        public async Task<IActionResult> Index(string searchString)
        {
            var statuses = from m in _context.Statuses
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                statuses = statuses.Where(s => s.Name.Contains(searchString));
            }

            return View(await statuses.ToListAsync());
        }

        // GET Statuses: /<controller>/Details/5
        public async Task<IActionResult> Details(int? id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "Поиск по фразе: " + searchString;
        }

        // GET Edit Status: /<controller>/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Name,Description")] Status status)
        {
            if (Id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Statuses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Statuses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Name,Description")] Status status)
        {
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(status);
        }

        // GET: Statuses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses.FindAsync(id);
            _context.Statuses.Remove(status);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(object Name)
        {
            throw new NotImplementedException();
        }
    }
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Statuses/Create.cshtml
@model LogisticManagerWorkspace.Models.Status

@{
    ViewData["Title"] = "Создание";
}

<h1>Редактирование:</h1>

<h4>Статус:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Statuses/Details.cshtml
@model LogisticManagerWorkspace.Models.Status

@{
    ViewData["Title"] = "Статус " + Model.Name;
}

<div>
    <h4>Статус "@Html.DisplayFor(model => model.Name)":</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a> |
    <a asp-action="Index">Назад к списку</a>
</div>

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Statuses/Edit.cshtml
@model LogisticManagerWorkspace.Models.Status

@{
    ViewData["Title"] = "Редактирование";
}

<h1>Редактирование:</h1>

<h4>Статус</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsC/LogisticManagerWorkspace/LogisticManagerWorkspace/Views/Statuses/Index.cshtml
@model IEnumerable<LogisticManagerWorkspace.Models.Status>
@{
    ViewData["Title"] = "Статусы услуги";
}

<h2>Статусы услуги</h2>

<p>Статусы услуг, предоставляемых клиентам:</p>

<p>
    <a asp-action="Create">Добавить</a>
</p>

<form asp-controller="Statuses" asp-action="Index" method="get">
    <p>
        Поиск по названию: <input type="text" name="SearchString">
        <input type="submit" value="Поиск" />
        <a asp-action="Index" class="btn btn-alert">Очистить</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редактирование</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Подробнее</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>